server:
  port: 8888
spring:
  application:
    name: configuration-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JamesHare/config-as-code-poc-properties-repo
          default-label: main